### ISSUE TITLE
Can't install docker

### ISSUE THREAD

**Issue by Fotz** [WAGO/docker-ipk#2]
Hi  !

Have some issues to install Docker !
I've already downloaded the IPK file, and uploaded on my PFC200, but after the Activation submit, there is a error (and that's ok as you said), but no docker command on my PFC.

I've checked to install it manually with the opkg command, but I guess my PFC can't install it cause my / partition is only 12M available.

So I checked mannually, but Docker ipk need need 115M !
But my / partition only got 82M as total size.. So how can we install it ?!

Then, i've tryied to install it on my SD card with the "-o" option on the opkg command.
But doesn't work, cause "Not selecting docker 18.09.0 due to incompatible architecture."

Dunno what to do now :/ !

Can you help me :( ?

Info :
- WAGO 750-8202 PFC200 CS 2ETH RS
- Firmware 03.00.35(12)

**Comment by Helmut-Saal** [comment]
Docker did only work on PFC G2 devices because the flash inside G1 Devices is to small

**Comment by Helmut-Saal** [comment]
readme excerpt: 
Wago PFC Generation 2 (e.g. 750-8212, 750-8213..) or Wago Touch Panel 600 (e.g 0762-4104, 0762-4103..) with min. firmware 12 or higher installed in flash.

**Comment by Fotz** [comment]
Hi

It's a 750-8202, so I guess it's Gen 1, I didnt found generation
informations
Firmware 12 !

Le sam. 23 nov. 2019 à 18:13, Helmut Saal <notifications@github.com> a
écrit :

**Comment by Ekristoffe** [comment]
Hello
There is a way to do it but, the performance will be reduced.
I only use it on a PFC200 G1 for development purpose.
Use a SD card to update the firmware to the latest version, use the create image to copy the firmware from the SD card to the Internal memory.
Switch off the power supply, eject the SD card and boot the PFC from the interna memory.
When the PFC is booted, insert the SD card again. In the create image page, select the full SD card size and copy the FW from the internal memory to the SD card.
Reboot the PFC and let it boot from the SD card.
You should now be able to install docker.
But I really want to empathize this should be used only in last resort case and just for testing/development purpose, never for production.

**Comment by Fotz** [comment]
Hi again

Thanks for this information, i'll won't try that yeah !
There is a way to install the Node-RED ipk without Docker implementation ?

I don't think so, i'll do with another way or maybe with external server :)

Thanks again !

**Comment by Helmut-Saal** [comment]
Yes, all can compile all packages by using the SDK, see dicribtion above.
But no support or help from wago for that....sorry.
