### ISSUE TITLE
Docker Update/Upgrade

### ISSUE THREAD

**Issue by Ekristoffe** [WAGO/docker-ipk#3]
Hello, 
New release for docker, nice.
Nothing about upgrade in the Read-me, so I search on the docker doc and nothing about loosing data.
I thought it was as easy as upgrading a container just use the ipk and everything goes nice and smooth, damned i was so wrong....
After the upgrade where are my containers ?
Everything is gone and there is no warning nowhere about loosing anything ...
In the opkg i saw this:
```
_DOCKER_ETC="/etc/docker/"
DOCKER_DATA="/home/docker/"

# clean up files that are generated by dockerd
if [ -z "$DESTDIR" ]; then
	rm -rf "$DOCKER_ETC"

	umount -fl "$DOCKER_DATA"
	rm -rf "$DOCKER_DATA"
fi

exit 0_
```
Seriously ?
No warning about anything and the script delete all docker data.

**Comment by jsparmann** [comment]
Yes, thanks for the description and the note. We have add an warning message and we will fix the lost of all docker data. There is no reason to delete the data.

**Comment by Helmut-Saal** [comment]
Hi, thanks again for the notification.
We fixed this issue, please try.

**Comment by Ekristoffe** [comment]
Hello all,
The problem is now fixed.
Thank you !
