### ISSUE TITLE
Docker command not found

### ISSUE THREAD

**Issue by ITBartlomiejWozniak** [WAGO/docker-ipk#4]
After docker instalation on PFC200 through web-based management I connected to plc via ssh. 
I am getting docker not found.

**Comment by jsparmann** [comment]
Please copy the docker ipk to the device and make a re-install with the following command: opkg install --force-reinstall **docker**.ipk. All on the ssh console. In case off an error, please post the output messages.

**Comment by ITBartlomiejWozniak** [comment]
It works. thanks
