### ISSUE TITLE
Not enough space on PFC200 G2

### ISSUE THREAD

**Issue by LuckyLukeCH** [WAGO/docker-ipk#7]
Hello,

We tried to install the Docker on PFC200 G2.

Here is the log:
Feb 26 03:09:36 PFC200V3-4F5C9C activate_download [2155] [Error]: [by shell command] (/usr/bin/opkg install /var/downloads/update-script/docker_20.10.5_armhf.ipk)
Feb 26 03:10:52 PFC200V3-4F5C9C activate_download [2232] [Error]: [internal error] (path /var/downloads/update-script/ is empty)

It is a fresh V16 installation.
It seems, that the space on the internal flash is not enough:

df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root               126.7M    109.9M     10.0M  92% /
devtmpfs                245.9M      4.0K    245.9M   0% /dev
none                    246.4M     16.0K    246.4M   0% /tmp
none                    246.4M         0    246.4M   0% /media
none                      4.0M    172.0K      3.8M   4% /var/log
none                    246.4M    148.0K    246.2M   0% /var/run
none                    246.4M         0    246.4M   0% /var/lock
none                    246.4M         0    246.4M   0% /var/tmp
none                    246.4M         0    246.4M   0% /sys/fs/cgroup
tmpfs                   246.4M    116.0K    246.3M   0% /run
/dev/mmcblk0p1           16.0M      2.7M     13.2M  17% /boot/loader

Thank you for your help and regards,
Lukas Gaam

**Comment by LuckyLukeCH** [comment]
We just compared to an older PFC200 G2 an the result is the following:

df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root               239.9M     76.6M    150.5M  34% /
devtmpfs                246.7M      4.0K    246.7M   0% /dev
none                    246.7M      4.0K    246.7M   0% /tmp
none                    246.7M         0    246.7M   0% /media
none                      4.0M    224.0K      3.8M   5% /var/log
none                    246.7M     60.0K    246.6M   0% /var/run
none                    246.7M         0    246.7M   0% /var/lock
none                    246.7M         0    246.7M   0% /var/tmp
tmpfs                   246.7M      4.0K    246.7M   0% /dev
tmpfs                   246.7M     56.0K    246.6M   0% /run
/dev/mmcblk1p1           63.8M     22.4M     41.4M  35% /boot
/dev/mmcblk1p5            1.9G      7.3M      1.8G   0% /home

uname -a 

Old-System
Linux PFC200V3-450D58 4.9.47-rt37-w02.02.00_01+14 #1 PREEMPT RT Thu Jul 19 13:54:19 UTC 2018 armv7l GNU/Linux

New/Fresh-System
Linux PFC200V3-4F5C9C 4.9.146-rt125w02.08.01 #1 PREEMPT RT Wed May 6 08:51:58 UTC 2020 armv7l GNU/Linux

**Comment by LuckyLukeCH** [comment]
WBM Device-Status on the new/fresh-System

Product Description WAGO 750-8212 PFC200 G2 2ETH RS
Ordernumber 750-8212
Serial SN20211029T071837-1491055#PFC|0030DE4F5C9C
License Information Codesys-Runtime-License
Firmware Revision 03.04.10(16)

**Comment by LuckyLukeCH** [comment]
Just realized, that the system booted from the SD-Card.
After normal booting the installation worked.

Regards
Lukas Gaam

**Comment by Helmut-Saal** [comment]
Hello,  please take care, such support questions should be placed to Wago Support Hotline. On Github we only support the posted stuff. THX.
