### ISSUE TITLE
Could you add libseccomp2 library to docker package?

### ISSUE THREAD

**Issue by bashlakov** [WAGO/docker-ipk#8]
I've expereincing problem with running latest HomeAssistant container without --privileged flag. Tho container output is:
`Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted`

This problem also discussed here: https://community.home-assistant.io/t/migration-to-2021-7-fails-fatal-python-error-init-interp-main-cant-initialize-time/320648/11
It's not HomeAssistant specific problem, it's more latest python/docker interaction problem.

Solution is to add libseccomp2 library that is used by modern docker engine.

**Comment by Helmut-Saal** [comment]
Hi, maybe you add a start option:  --security-opt seccomp:unconfined 
To build the newest dockerengine is not so easy, because we build it from sources directly for the firmware. 
So updates could take a while, maybe the startflag fix your bug.

**Comment by bashlakov** [comment]
I temporary bypassed problem with --privileged flag, so I can wait for permanent solution.

**Comment by Helmut-Saal** [comment]
Since FW24 this is fixed.
